Repository koglak/bounswe574-2022-gr2, pull requests merged in 2022-12, with the labels that each got.

#44 Space forum addition
  userprofile/admin.py
  userprofile/forms.py
  userprofile/migrations/0036_question_answer.py
  userprofile/models.py
  userprofile/templates/includes/course.html
  userprofile/templates/includes/course2.html
  userprofile/templates/includes/sidebar.html
  userprofile/templates/userprofile/forum_page.html
  userprofile/templates/userprofile/question_detail.html
  userprofile/templates/userprofile/question_edit.html
  userprofile/templates/userprofile/space_metrics.html
  userprofile/urls.py
  userprofile/views.py
Labels: Coding Required, Priority: Significant, Effort Estimate: High, Merge

#48 case_detail template is updated, rating list is visible now even the …
  quiz/templates/quiz/case_detail.html
Labels: Priority: Low, Coding Required, Assignment, Effort Estimate: Low

#49 Case page update 4
  quiz/templates/quiz/case_detail.html
  quiz/views.py
  userprofile/templates/userprofile/case_list.html
  userprofile/templates/userprofile/case_page.html
Labels: bug, Coding Required, Priority: High, Effort Estimate: Low

#51 Murat mert home
  blog/templates/blog/base.html
  blog/templates/blog/home.html
  blog/views.py
  mysite/settings.py
  quiz/migrations/0005_questionlist_timestamp.py
  quiz/models.py
  userprofile/migrations/0033_course_timestamp_profile_timestamp.py
  userprofile/models.py
  userprofile/templates/includes/course2.html
Labels: Coding Required, Effort Estimate: High
